FROM node:22.10.0-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY package*.json ./

ENV NODE_ENV production
ENV WATCHPACK_POLLING true
ENV NEXT_WEBPACK_USEPOLLING true

ARG NEXT_PUBLIC_API_V1_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_V1_SERVER_URL
ARG NEXT_PUBLIC_API_SERVER_URL
ARG NEXT_MIRAGE_SERVER
ARG NEXT_PUBLIC_TEMP_USER_ROLES
ARG NEXT_PUBLIC_INVITE_TIME_HOURS
ARG NEXT_PUBLIC_FILE_DOWNLOAD_URL
ARG NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
ARG NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET
ARG NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_LOGIN
ARG NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_LOGOUT
ARG NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_REGISTER
ARG NEXT_PUBLIC_KEYCLOAK_BASE_URL
ARG NEXT_PUBLIC_KEYCLOAK_REALM
ARG NEXT_PUBLIC_KEYCLOAK_TEST_USERNAME
ARG NEXT_PUBLIC_KEYCLOAK_TEST_PASSWORD
ARG GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_LOCAL_ENV
ARG NEXT_PUBLIC_GTM_ID
ARG IDVT_SUPPLIER_API_KEY
ARG IDVT_SUPPLIER_BASE_URL

RUN npm install

COPY . /usr/src

RUN npm run build

EXPOSE 3000
CMD npm run start