const FORMAT_SHORT_DATE = "DD/MM/YYYY";
const FORMAT_DATE_DB = "YYYY-MM-DD HH:mm:ss";
const FORMAT_DISPLAY_SHORT_DATE = "MMM YYYY";
const FORMAT_DISPLAY_LONG_DATE = "D MMMM YYYY";
const FORMAT_DISPLAY_INPUT_DATE = "EEE MMM dd yyyy HH:mm:ss 'GMT'XXX (zzzz)";

export {
  FORMAT_SHORT_DATE,
  FORMAT_DATE_DB,
  FORMAT_DISPLAY_SHORT_DATE,
  FORMAT_DISPLAY_LONG_DATE,
  FORMAT_DISPLAY_INPUT_DATE,
};
