const FORMAT_SHORT_DATE = "DD/MM/YYYY";
const FORMAT_DATE_DB = "YYYY-MM-DD hh:mm:ss";
const FORMAT_DISPLAY_SHORT_DATE = "MMM YYYY";
const FORMAT_DISPLAY_LONG_DATE = "D MMMM YYYY";

export {
  FORMAT_SHORT_DATE,
  FORMAT_DATE_DB,
  FORMAT_DISPLAY_SHORT_DATE,
  FORMAT_DISPLAY_LONG_DATE,
};
