const VALIDATION_PASSWORD_FORMAT =
  /(?=[^a-z]*[a-z])(?=[^A-Z]*[A-Z])(?=\D*\d)(?=[^!#%\\?]*[!#%\\?])[A-Za-z0-9!#%\\?]{8,32}/;

const VALIDATION_PASSWORD_LENGTH = 8;
const VALIDATION_OTP_PASSCODE_LENGTH = 6;

const VALIDATION_POSTCODE_FORMAT = /[A-Z]{1,2}[0-9]{1,2} ?[0-9][A-Z]{2}/i;
const VALIDATION_COMPANY_NUMBER =
  /^((AC|ZC|FC|GE|LP|OC|SE|SA|SZ|SF|GS|SL|SO|SC|ES|NA|NZ|NF|GN|NL|NC|R0|NI|EN|\d{2}|SG|FE)\d{5}(\d|C|R))|((RS|SO)\d{3}(\d{3}|\d{2}[WSRCZF]|\d(FI|RS|SA|IP|US|EN|AS)|CUS))|((NI|SL)\d{5}[\dA])|(OC(([\dP]{5}[CWERTB])|([\dP]{4}(OC|CU))))$/;

const VALIDATION_CE_CERTIFICATION_NUMBER = /^[\w]{4}$/;

export {
  VALIDATION_PASSWORD_FORMAT,
  VALIDATION_PASSWORD_LENGTH,
  VALIDATION_OTP_PASSCODE_LENGTH,
  VALIDATION_POSTCODE_FORMAT,
  VALIDATION_COMPANY_NUMBER,
  VALIDATION_CE_CERTIFICATION_NUMBER,
};
