import { Status } from "@/components/ChipStatus";

const STATUS_ORDER = [
  Status.AFFILIATION_INVITED,
  Status.INVITED,
  Status.INVITE_SENT,
  Status.FORM_RECEIVED,
  Status.PENDING,
  Status.PROJECT_PENDING,
  Status.AFFILIATION_PENDING,
  Status.VALIDATION_IN_PROGRESS,
  Status.PROJECT_IN_PROGRESS,
  Status.MORE_ORG_INFO_REQ,
  Status.MORE_ORG_INFO_REQ_ESCALATION_MANAGER,
  Status.MORE_ORG_INFO_REQ_ESCALATION_COMMITTEE,
  Status.MORE_USER_INFO_REQ,
  Status.MORE_USER_INFO_REQ_ESCALATION_MANAGER,
  Status.MORE_USER_INFO_REQ_ESCALATION_COMITTEE,
  Status.VALIDATION_COMPLETE,
  Status.PROJECT_APPROVED,
  Status.AFFILIATION_APPROVED,
  Status.AFFILIATED,
  Status.ORG_VALIDATION_DECLINED,
  Status.USER_VALIDATION_DECLINED,
  Status.PROJECT_DECLINED_APPROVAL,
  Status.AFFILIATION_REJECTED,
  Status.ORG_LEFT_PROJECT,
  Status.AFFILIATION_LEFT,
  Status.USER_LEFT_PROJECT,
];

export const STATUS_ORDER_MAP = new Map(
  STATUS_ORDER.map((key: string, index) => [key, index])
);
