export const termsItems = [
  "understanding",
  "researcherUsage",
  "organisationUsage",
  "custodianUsage",
  "account",
  "acceptableUse",
  "intellectualProperty",
  "inputData",
  "liability",
  "disclaimers",
  "suspension",
  "changes",
  "thirdParty",
  "other",
  "law",
  "contact",
];
